// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.api.Services.Context;

#nullable disable

namespace server.api.Migrations
{
    [DbContext(typeof(SifocaContext))]
    partial class SifocaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("server.api.Models.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataAtualizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tb_Entrada");
                });

            modelBuilder.Entity("server.api.Models.Fundo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Tb_Fundo");

                    b.HasData(
                        new
                        {
                            Id = "caixa",
                            Total = 0m
                        });
                });

            modelBuilder.Entity("server.api.Models.Movimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Caixa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataAtualizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tb_Movimento");
                });

            modelBuilder.Entity("server.api.Models.Saida", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataAtualizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsável")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tb_Saida");
                });

            modelBuilder.Entity("server.api.Models.Entrada", b =>
                {
                    b.HasOne("server.api.Models.Movimento", "Movimento")
                        .WithMany("Entradas")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimento");
                });

            modelBuilder.Entity("server.api.Models.Saida", b =>
                {
                    b.HasOne("server.api.Models.Movimento", "Movimento")
                        .WithMany("Saidas")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimento");
                });

            modelBuilder.Entity("server.api.Models.Movimento", b =>
                {
                    b.Navigation("Entradas");

                    b.Navigation("Saidas");
                });
#pragma warning restore 612, 618
        }
    }
}
